language: php
php:
  - 7.1
sudo: required
services:
  - docker
install:
  - php composer.phar install --optimize-autoloader
script: docker-compose run --rm test
after_success:
  - docker-compose down
  - travis_retry php vendor/bin/coveralls -v