version: '2'
services:
  dynamodb:
    image: instructure/dynamo-local-admin

  redis:
    image: redis:latest

  test:
    image: revenuewire/docker-php7-xdebug:latest
    links:
        - dynamodb:dynamodb
        - redis:redis
    volumes:
        - $PWD:$PWD
    working_dir: $PWD
    command: ./vendor/bin/phpunit
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

